name: Deploy Frontend to S3

on:
    workflow_dispatch:

jobs:

  deploy-fe:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    env:
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION}}
      REACT_APP_AWS_REGION: ${{ vars.AWS_DEFAULT_REGION}}
      REACT_APP_S3_BUCKET: vclipper-frontend-prod
      REACT_APP_API_ENDPOINT: http://ad0b74e37acc44d0a97e50f8f05b6796-2091971183.us-east-1.elb.amazonaws.com
      REACT_APP_USER_POOL_ID: us-east-1_vP3O4reHW
      REACT_APP_USER_POOL_CLIENT_ID: 1sb936hbm9g4ruq0i3qel1fndb
      WEBSITE_URL: ${{ vars.WEBSITE_URL}}
      HTTPS_URL: ${{ vars.HTTPS_URL}}
      REACT_APP_USE_MOCK_AUTH: ${{ vars.MOCK}}
      REACT_APP_USE_MOCK_VIDEO: ${{ vars.MOCK}}
      TIMEOUT: "30"
    steps:
      - name: Checkout FE Repo
        uses: actions/checkout@v3
        with:
          repository: 'fiap-9soat-snackbar/vclipper_fe'
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Gerar .env a partir de template
        run: |
              cp .env.template .env.template.bkp

              export REACT_APP_AWS_REGION="${{ env.REACT_APP_AWS_REGION }}"
              export REACT_APP_S3_BUCKET="${{ env.REACT_APP_S3_BUCKET }}"
              export REACT_APP_API_ENDPOINT="${{ env.REACT_APP_API_ENDPOINT }}"
              export REACT_APP_USER_POOL_ID="${{ env.REACT_APP_USER_POOL_ID }}"
              export REACT_APP_USER_POOL_CLIENT_ID="${{ env.REACT_APP_USER_POOL_CLIENT_ID }}"
              export REACT_APP_USE_MOCK_AUTH="${{ env.REACT_APP_USE_MOCK_AUTH }}"
              export REACT_APP_USE_MOCK_VIDEO="${{ env.REACT_APP_USE_MOCK_VIDEO }}"
              export WEBSITE_URL="${{ env.WEBSITE_URL }}"
              export HTTPS_URL="${{ env.HTTPS_URL }}"
              export TIMEOUT="${{ env.TIMEOUT }}"
          
              envsubst < .env.template > .env

              cat .env
        
      - name: Instalar dependências
        run: npm install

      - name: Build do projeto + Deploy no S3
        run: |
               ./prod-deploy.sh